bar:
  height: 40
  location: top
  background: 222222ff
  left: 
    - dwl:
        number-of-tags: 6
        dwl-info-filename: "/tmp/dwl_info"
        name-of-tags: [ , 󰈹, , 4, 5, 6 ]
        content:
          list:
            items:
              - map:
                  conditions:
                    # default tag
                    id == 0: {string: {text: "{layout} {title}"}}
                    selected: {string: {text: "->   {name}  "}}
                    ~empty: {string: {text: "   {name}   "}}
                    urgent: {string: {text: "=>   {name}   <="}}
              
